# -*- coding: utf-8 -*-
"""tv_schedule_ga.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cijdmiTdSrTYBd9YBhZN35Ss8R6WYBMy
"""

import csv
import random
import pandas as pd

# === Read CSV ===
def read_csv_to_dict(file_path):
    program_ratings = {}
    with open(file_path, mode='r', newline='') as file:
        reader = csv.reader(file)
        header = next(reader)
        for row in reader:
            program = row[0]
            ratings = [float(x) for x in row[1:]]
            program_ratings[program] = ratings
    return program_ratings


# === Fitness Function ===
def fitness_function(schedule, ratings):
    total_rating = 0
    for time_slot, program in enumerate(schedule):
        total_rating += ratings[program][time_slot]
    return total_rating


# === Initialize Population ===
def initialize_pop(programs):
    population = []
    for _ in range(50):  # small population for performance
        schedule = programs.copy()
        random.shuffle(schedule)
        population.append(schedule)
    return population


# === Crossover ===
def crossover(schedule1, schedule2):
    crossover_point = random.randint(1, len(schedule1) - 2)
    child1 = schedule1[:crossover_point] + schedule2[crossover_point:]
    child2 = schedule2[:crossover_point] + schedule1[crossover_point:]
    return child1, child2


# === Mutation ===
def mutate(schedule, all_programs):
    mutation_point = random.randint(0, len(schedule) - 1)
    schedule[mutation_point] = random.choice(all_programs)
    return schedule


# === Main GA ===
def genetic_algorithm(ratings, crossover_rate=0.8, mutation_rate=0.2, generations=100, pop_size=50, elitism_size=2):
    all_programs = list(ratings.keys())
    all_time_slots = list(range(6, 24))
    population = initialize_pop(all_programs)

    for _ in range(generations):
        population.sort(key=lambda s: fitness_function(s, ratings), reverse=True)
        new_population = population[:elitism_size]

        while len(new_population) < pop_size:
            p1, p2 = random.sample(population, 2)
            if random.random() < crossover_rate:
                c1, c2 = crossover(p1, p2)
            else:
                c1, c2 = p1.copy(), p2.copy()

            if random.random() < mutation_rate:
                c1 = mutate(c1, all_programs)
            if random.random() < mutation_rate:
                c2 = mutate(c2, all_programs)

            new_population.extend([c1, c2])

        population = new_population[:pop_size]

    best_schedule = max(population, key=lambda s: fitness_function(s, ratings))
    total_rating = fitness_function(best_schedule, ratings)

# Ensure same length between schedule and time slots
all_time_slots = list(range(6, 24))
programs_fixed = best_schedule[:len(all_time_slots)]

# If the schedule is shorter, pad it with empty values
if len(programs_fixed) < len(all_time_slots):
    programs_fixed += ["-"] * (len(all_time_slots) - len(programs_fixed))

schedule_df = pd.DataFrame({
    "Time Slot": [f"{t:02d}:00" for t in all_time_slots],
    "Program": programs_fixed
})

# Add total rating info
schedule_df["Total Rating"] = [""] * (len(all_time_slots) - 1) + [total_rating]

    return schedule_df, total_rating
